config/routes.rb
Rails.application.routes.draw do
  root to: 'skus#index'
  resources :skus, only: [:index]
  resources :uploads, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sku.rb
class Sku < ApplicationRecord
  belongs_to :supplier

  validates :field_1, presence: true
  validates :field_2, presence: true
  validates :field_3, presence: true
  validates :field_4, presence: true
  validates :field_5, presence: true
  validates :field_6, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :skus

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/upload.rb
class Upload < ApplicationRecord
  include AASM

  CSV_FILENAME_REGEX = /(?<upload_type>supplier(s)?|sku(s)?)[\w\d\-\_\(\)]*\.csv\z/i

  has_attached_file :csv_file
  validates_attachment :csv_file, content_type: { content_type: ["text/comma-separated-values", "text/csv", "text/plain"] },
                       presence: true, matches: [CSV_FILENAME_REGEX]
  validates :rows_count, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :processed_rows_count, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :processed_rows_count, numericality: { less_than_or_equal_to: :rows_count }, if: :rows_count
  validates :upload_type, inclusion: [:supplier, :sku]

  aasm :status do
    state :pending, initial: true
    state :in_progress, :finished

    event :run do
      transitions from: :pending, to: :in_progress
    end

    event :finish do
      transitions from: :in_progress, to: :finished, guard: -> { processed_rows_count <= rows_count }
    end
  end

  def schedule_parse_csv_job
    ParseCsvJob.perform_later(self)
  end

  def parse_csv!
    UploadCsvParser.for(self).parse!
  end

  def upload_type
    return @upload_type if @upload_type

    if match = csv_file_file_name&.match(CSV_FILENAME_REGEX)
      @upload_type ||= match[:upload_type].downcase.singularize.to_sym
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/skus_controller.rb
class SkusController < ApplicationController
  def index
    @skus = Sku.preload(:supplier).page(params[:page])
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new upload_params
    if @upload.save
      @upload.schedule_parse_csv_job
      redirect_to skus_path, flash: { success: 'Successfully created new upload' }
    else
      render :new
    end
  end

  def index
    @uploads = Upload.page(params[:page])
  end

  private

  def upload_params
    params.require(:upload).permit(:csv_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.haml
.error_explanation.alert.alert-danger{class: "#{dom_class(object)}_errors"}
  %h5
    = "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.model_name.human} from being saved:"
  %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/layouts/_flash_messages.haml
#flash-messages
  - flash.each do |type, message|
    .alert{class: "alert-#{type}", role: 'alert'}
      %button.close{"data-dismiss" => "alert"} ×
      = message

app/views/layouts/_navigation.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-faded
  %ul.navbar-nav
    %li.nav-item{ class: controller.kind_of?(SkusController) ? 'active' : ''}
      = link_to 'Skus', skus_path, class: 'nav-link'
    %li.nav-item{ class: controller.kind_of?(UploadsController) ? 'active' : '' }
      = link_to 'Uploads', uploads_path, class: 'nav-link'

app/views/layouts/application.haml
!!!
%html
  %head
    %title CsvDemo
    = csrf_meta_tags
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  %body
    .container-fluid
      = render 'layouts/navigation'
      = render 'layouts/flash_messages'
      = yield

app/views/skus/index.haml
%br
.row
  .col-xs-12
    = link_to 'Upload CSV', new_upload_path, class: 'btn btn-outline-primary'
%br

%table.table.skus
  %thead
    %tr
      %th= Sku.human_attribute_name(:id)
      %th= Supplier.model_name.human
      %th= Sku.human_attribute_name(:field_1)
      %th= Sku.human_attribute_name(:field_2)
      %th= Sku.human_attribute_name(:field_3)
      %th= Sku.human_attribute_name(:field_4)
      %th= Sku.human_attribute_name(:field_5)
      %th= Sku.human_attribute_name(:field_6)
      %th= Sku.human_attribute_name(:price)
  %tbody
    - @skus.each do |sku|
      %tr{id: dom_id(sku)}
        %td.id= sku.id
        %td.supplier= sku.supplier.name
        %td.field_1= sku.field_1
        %td.field_2= sku.field_2
        %td.field_3= sku.field_3
        %td.field_4= sku.field_4
        %td.field_5= sku.field_5
        %td.field_6= sku.field_6
        %td.price= number_to_currency(sku.price)

= will_paginate @skus, inner_window: 2, outer_window: 0, renderer: 'Pagination::BootstrapRenderer', previous_label: '&larr;'.html_safe, next_label: '&rarr;'.html_safe

app/views/uploads/index.haml
%br
.row
  .col-xs-12
    = link_to 'Upload CSV', new_upload_path, class: 'btn btn-outline-primary'
%br

%table.table.uploads
  %thead
    %tr
      %th= Upload.human_attribute_name(:id)
      %th= Upload.human_attribute_name(:status)
      %th= Upload.human_attribute_name(:csv_file_name)
  %tbody
    - @uploads.each do |upload|
      %tr{id: dom_id(upload)}
        %td.id= upload.id
        %td.status
          = t(upload.status, scope: 'upload_status', processed_rows_count: upload.processed_rows_count, rows_count: upload.rows_count)
          - if upload.invalid_rows_count.positive?
            = t('unprocessed_rows_count', count: upload.invalid_rows_count)
        %td.csv-file-name= upload.csv_file_file_name

= will_paginate @uploads, inner_window: 2, outer_window: 0, renderer: 'Pagination::BootstrapRenderer', previous_label: '&larr;'.html_safe, next_label: '&rarr;'.html_safe

app/views/uploads/new.haml
- if @upload.errors.any?
  = render 'layouts/error_messages', object: @upload

= form_for @upload, html: { multipart: true } do |f|
  .form-group
    = f.label :csv_file, 'CSV File'
    = f.file_field :csv_file, class: 'form-control-file'
    %small.form-text.text-muted Only skus.csv and suppliers.csv are allowed
  = f.submit 'Submit', class: 'btn btn-primary'